import { CalculatorMeta } from '../types';

export const ALL_CALCULATORS: CalculatorMeta[] = [
  // Financial (6)
  {
    id: 'emi',
    name: 'Loan & EMI Calculator',
    shortName: 'Loan EMI',
    category: 'financial',
    description: 'Calculate monthly loan EMI, total interest, and full 40-year amortization schedules.',
    icon: 'Landmark',
    keywords: ['loan', 'emi', 'car', 'personal loan', 'interest', 'amortization'],
  },
  {
    id: 'compound',
    name: 'Compound Interest & Savings',
    shortName: 'Compound',
    category: 'financial',
    description: 'Project wealth growth with recurring contributions and compound frequency.',
    icon: 'TrendingUp',
    keywords: ['investment', 'interest', 'savings', 'growth', 'stocks', 'future value'],
  },
  {
    id: 'mortgage',
    name: 'Mortgage & Escrow',
    shortName: 'Mortgage',
    category: 'financial',
    description: 'Complete home loan estimate including property tax, insurance, and PMI.',
    icon: 'Home',
    keywords: ['home loan', 'house', 'pmi', 'property tax', 'escrow', 'real estate'],
  },
  {
    id: 'tip',
    name: 'Tip & Bill Splitter',
    shortName: 'Tip Splitter',
    category: 'financial',
    description: 'Split dining checks, calculate tips, and round totals fairly.',
    icon: 'Receipt',
    keywords: ['restaurant', 'dining', 'bill', 'share', 'gratuity', 'friends'],
  },
  {
    id: 'discount',
    name: 'Discount & Sales Tax',
    shortName: 'Discount/Tax',
    category: 'financial',
    description: 'Compute final checkout price with percentage markdowns and local sales tax.',
    icon: 'Tag',
    keywords: ['shopping', 'sale', 'clearance', 'coupon', 'retail', 'savings'],
  },
  {
    id: 'currency',
    name: 'Currency Converter',
    shortName: 'Currency',
    category: 'financial',
    description: 'Offline exchange rates matrix with persistent custom rate overrides.',
    icon: 'Coins',
    keywords: ['forex', 'exchange', 'usd', 'eur', 'inr', 'gbp', 'travel'],
  },

  // Health (4)
  {
    id: 'bmi',
    name: 'BMI & Body Health',
    shortName: 'BMI Health',
    category: 'health',
    description: 'Metric and imperial Body Mass Index with medical disclaimer and health brackets.',
    icon: 'Activity',
    keywords: ['weight', 'height', 'fitness', 'obesity', 'body', 'health'],
  },
  {
    id: 'bmr',
    name: 'BMR & Calorie Needs',
    shortName: 'BMR Calories',
    category: 'health',
    description: 'Mifflin-St Jeor basal metabolic rate and daily calorie targets for weight goals.',
    icon: 'Flame',
    keywords: ['metabolism', 'diet', 'calories', 'tdee', 'nutrition', 'macros'],
  },
  {
    id: 'bodyfat',
    name: 'Body Fat Percentage',
    shortName: 'Body Fat %',
    category: 'health',
    description: 'US Navy circumference method for estimated body composition.',
    icon: 'HeartPulse',
    keywords: ['fat', 'lean mass', 'navy', 'fitness', 'waist', 'measurements'],
  },
  {
    id: 'water',
    name: 'Water Intake & Hydration',
    shortName: 'Hydration',
    category: 'health',
    description: 'Daily recommended fluid volume based on body mass, climate, and exercise.',
    icon: 'Droplet',
    keywords: ['water', 'hydration', 'drinks', 'fluids', 'wellness', 'daily'],
  },

  // Math & Everyday (5)
  {
    id: 'age',
    name: 'Age & Date Difference',
    shortName: 'Age & Dates',
    category: 'math',
    description: 'Precise years, months, days lived, leap year handling, and birthday countdown.',
    icon: 'Calendar',
    keywords: ['birthday', 'calendar', 'anniversary', 'days', 'time between'],
  },
  {
    id: 'percentage',
    name: 'Percentage Calculator',
    shortName: 'Percentages',
    category: 'math',
    description: 'Three percentage modes: percent of, what percent, and percentage change.',
    icon: 'Percent',
    keywords: ['ratio', 'proportion', 'fraction', 'growth', 'decrease'],
  },
  {
    id: 'scientific',
    name: 'Scientific Math Calculator',
    shortName: 'Math / Sci',
    category: 'math',
    description: 'Expressions, brackets, powers, square roots, trigonometry, and logarithms.',
    icon: 'Calculator',
    keywords: ['math', 'expression', 'sin', 'cos', 'sqrt', 'power', 'algebra'],
  },
  {
    id: 'time',
    name: 'Time & Duration',
    shortName: 'Time Duration',
    category: 'math',
    description: 'Add or subtract time, calculate shift intervals and decimal work hours.',
    icon: 'Clock',
    keywords: ['hours', 'minutes', 'timesheet', 'shift', 'work hours', 'timer'],
  },
  {
    id: 'gpa',
    name: 'GPA & Grade Calculator',
    shortName: 'GPA Grade',
    category: 'math',
    description: 'Weighted 4.0 collegiate GPA based on course letter grades and credits.',
    icon: 'GraduationCap',
    keywords: ['college', 'university', 'grades', 'score', 'semester', 'courses'],
  },

  // Conversions & Engineering (5)
  {
    id: 'unit',
    name: 'Unit Converter',
    shortName: 'Unit Convert',
    category: 'conversion',
    description: 'Convert length, mass, area, volume, and speed across standard units.',
    icon: 'ArrowLeftRight',
    keywords: ['metric', 'imperial', 'miles', 'km', 'pounds', 'kg', 'gallons'],
  },
  {
    id: 'temperature',
    name: 'Temperature Converter',
    shortName: 'Temperature',
    category: 'conversion',
    description: 'Celsius, Fahrenheit, and Kelvin with strict absolute zero limits.',
    icon: 'Thermometer',
    keywords: ['weather', 'celsius', 'fahrenheit', 'kelvin', 'heat', 'cold'],
  },
  {
    id: 'fuel',
    name: 'Fuel Cost & Mileage',
    shortName: 'Fuel Mileage',
    category: 'conversion',
    description: 'Estimate road trip fuel consumption, cost per mile/km, and total fuel budget.',
    icon: 'Fuel',
    keywords: ['gas', 'petrol', 'mpg', 'liters', 'road trip', 'travel cost'],
  },
  {
    id: 'datatransfer',
    name: 'Data Transfer & Speed',
    shortName: 'Data Speed',
    category: 'conversion',
    description: 'Calculate download and upload duration for large files at given bandwidth.',
    icon: 'Wifi',
    keywords: ['download', 'upload', 'bandwidth', 'gigabytes', 'mbps', 'internet'],
  },
  {
    id: 'numberbase',
    name: 'Number Base Converter',
    shortName: 'Number Base',
    category: 'conversion',
    description: 'Convert between Decimal, Binary, Octal, and Hexadecimal representations.',
    icon: 'Binary',
    keywords: ['binary', 'hex', 'octal', 'decimal', 'bits', 'programmer', 'bytes'],
  },
];
